basePath: /
host: localhost:9888
info:
  contact: {}
  description: This is API Server for chat
  title: Swagger Example API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
